# 🛰️ SatQuery AI — RS-VLM Fine-Tuning with FMoW 2015

### Fine-tune Qwen2-VL-7B on Satellite VQA & Grounding using 4-bit QLoRA

**Dataset:** FMoW 2015 RGB Dataset

**Selected Classes:**
- Airport
- Crop Field
- Factory / Powerplant
- Lake / Pond
- Port

**Training Dataset:**
- 500 RGB satellite images
- 100 images per class
- Training split
- FMoW 2015

**Model:** Qwen2-VL-7B-Instruct  
**Fine-Tuning:** 4-bit QLoRA  
**GPU:** NVIDIA Tesla T4

---

### Instructions

1. Go to **Runtime → Change runtime type → T4 GPU**.
2. Run the notebook cells sequentially.
3. The FMoW images and dataset files are stored in Google Drive.
4. The next stage will prepare the images into the required **VQA training format**.
5. Fine-tune Qwen2-VL using QLoRA.
6. Save the trained LoRA adapter for integration with **SatQuery AI**.

## 1. Verify GPU Hardware Acceleration

In [1]:
!nvidia-smi

Fri Sep 25 10:22:52 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   44C    P8             16W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

## 2. Install Dependencies (QLoRA, PEFT, Transformers, BitsAndBytes)

In [2]:
!pip install -q -U "bitsandbytes>=0.46.1" "transformers>=4.45.0" peft accelerate datasets torchvision "pillow>=10.4.0"

print("✅ Dependencies installed.")
print("⚠️ IMPORTANT: If this is your first time running this notebook, restart the Colab session now.")
print("   Go to: Runtime → Restart session")
print("   After restarting, reconnect to the GPU if needed, then continue running the notebook from the next cell.")

✅ Dependencies installed.
⚠️ IMPORTANT: In Google Colab, click 'Runtime' -> 'Restart session' now to reload Pillow before proceeding.

In [13]:
from google.colab import drive
drive.mount('/content/drive')

print("Google Drive mounted successfully.")

Mounted at /content/drive
Google Drive mounted successfully.

## 3. Prepare FMoW 2015 RGB Dataset

Select 500 training images from 5 classes:
- airport
- crop_field
- factory_or_powerplant
- lake_or_pond
- port

Target: 100 unique training images per class.
The completed dataset will be saved to Google Drive.

In [5]:
# Install AWS CLI for downloading selected FMoW RGB images
!pip -q install awscli

print("✅ AWS CLI installed.")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.2/20.2 MB 55.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 570.5/570.5 kB 40.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sphinx 8.2.3 requires docutils<0.22,>=0.20, but you have docutils 0.19 which is incompatible.
✅ AWS CLI installed.

In [6]:
import os
import json
import subprocess

# FMoW RGB AWS location
S3_ROOT = "s3://spacenet-dataset/Hosted-Datasets/fmow/fmow-rgb"

# Local working folder
LOCAL_ROOT = "/content/fmow_2015"
os.makedirs(LOCAL_ROOT, exist_ok=True)

# Google Drive backup location
DRIVE_ROOT = "/content/drive/MyDrive/SatQuery_AI/FMoW_2015"
os.makedirs(DRIVE_ROOT, exist_ok=True)

print("Local folder:", LOCAL_ROOT)
print("Drive backup:", DRIVE_ROOT)
print("✅ FMoW workspace ready.")

Local folder: /content/fmow_2015
Drive backup: /content/drive/MyDrive/SatQuery_AI/FMoW_2015
✅ FMoW workspace ready.

In [7]:
# Download the FMoW RGB manifest
manifest_path = f"{LOCAL_ROOT}/manifest.json.bz2"

!aws s3 cp --no-sign-request \
    s3://spacenet-dataset/Hosted-Datasets/fmow/fmow-rgb/manifest.json.bz2 \
    "{manifest_path}"

print("✅ FMoW manifest downloaded.")
print("Path:", manifest_path)

download: s3://spacenet-dataset/Hosted-Datasets/fmow/fmow-rgb/manifest.json.bz2 to fmow_2015/manifest.json.bz2
✅ FMoW manifest downloaded.
Path: /content/fmow_2015/manifest.json.bz2

In [8]:
import bz2
import json

manifest_path = "/content/fmow_2015/manifest.json.bz2"

with bz2.open(manifest_path, "rt") as f:
    manifest = json.load(f)

print("Manifest loaded successfully.")
print("Number of entries:", len(manifest))
print("Type:", type(manifest))

Manifest loaded successfully.
Number of entries: 2095393
Type: <class 'list'>

## 4. Prepare FMoW VQA Training Dataset

Create VQA question-answer records from the 500 verified FMoW RGB images.

Each image will be paired with a satellite-image classification question and its FMoW category as the answer.

In [16]:
import json
import os

DRIVE_ROOT = "/content/drive/MyDrive/SatQuery_AI/FMoW_2015"

input_json = os.path.join(
    DRIVE_ROOT,
    "fmow_2015_final_500_training.json"
)

vqa_json = os.path.join(
    DRIVE_ROOT,
    "fmow_2015_vqa_500_training.json"
)

with open(input_json, "r") as f:
    records = json.load(f)

print("Loaded records:", len(records))

vqa_records = []

for item in records:
    image_path = os.path.join(DRIVE_ROOT, item["image"])

    vqa_records.append({
        "image": image_path,
        "category": item["category"],
        "question": "What type of location is shown in this satellite image?",
        "answer": item["category"].replace("_", " ")
    })

with open(vqa_json, "w") as f:
    json.dump(vqa_records, f, indent=2)

print("VQA dataset saved to:", vqa_json)
print("VQA records:", len(vqa_records))

Loaded records: 500
VQA dataset saved to: /content/drive/MyDrive/SatQuery_AI/FMoW_2015/fmow_2015_vqa_500_training.json
VQA records: 500

In [17]:
with open(vqa_json, "r") as f:
    vqa_records = json.load(f)

print("Total VQA records:", len(vqa_records))

categories = {}

for item in vqa_records:
    categories[item["category"]] = categories.get(item["category"], 0) + 1

print("\nCategory counts:")

for category, count in sorted(categories.items()):
    print(f"{category}: {count}")

if len(vqa_records) == 500 and all(count == 100 for count in categories.values()):
    print("\n🎉 VQA DATASET VERIFIED: 500 records, 100 per class")
else:
    print("\n❌ Dataset counts need to be checked.")

Total VQA records: 500

Category counts:
airport: 100
crop_field: 100
factory_or_powerplant: 100
lake_or_pond: 100
port: 100

🎉 VQA DATASET VERIFIED: 500 records, 100 per class

## 5. Load Base VLM in 4-bit NF4 Precision (`Qwen2-VL-7B-Instruct`)

In [18]:
!pip uninstall -y torchaudio

print("✅ Incompatible TorchAudio removed.")

Found existing installation: torchaudio 2.11.0+cu128
Uninstalling torchaudio-2.11.0+cu128:
  Successfully uninstalled torchaudio-2.11.0+cu128
✅ Incompatible TorchAudio removed.

In [19]:
import torch
from transformers import (
    Qwen2VLForConditionalGeneration,
    AutoProcessor,
    BitsAndBytesConfig
)

model_id = "Qwen/Qwen2-VL-7B-Instruct"

import bitsandbytes as bnb

print("bitsandbytes version:", bnb.__version__)

processor = AutoProcessor.from_pretrained(model_id)

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True
)

model = Qwen2VLForConditionalGeneration.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.float16
)

print("✅ Base Qwen2-VL-7B successfully loaded in 4-bit precision!")

bitsandbytes version: 0.50.2

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

preprocessor_config.json:   0%|          | 0.00/347 [00:00<?, ?B/s]

chat_template.json:   0%|          | 0.00/1.05k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.20k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/4.19k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/56.5k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/730 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/244 [00:00<?, ?B/s]

✅ Base Qwen2-VL-7B successfully loaded in 4-bit precision!

## 6. Configure LoRA (Parameter-Efficient Fine-Tuning)

In [20]:
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

model = prepare_model_for_kbit_training(model)

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

model = get_peft_model(model, lora_config)

model.print_trainable_parameters()

trainable params: 10,092,544 || all params: 8,301,468,160 || trainable%: 0.1216

## 7. Fine-Tuning Execution

In [27]:
import os
import json
import subprocess

DRIVE_ROOT = "/content/drive/MyDrive/SatQuery_AI/FMoW_2015"
input_json = os.path.join(
    DRIVE_ROOT,
    "fmow_2015_final_500_training.json"
)

S3_ROOT = "s3://spacenet-dataset/Hosted-Datasets/fmow/fmow-rgb"

with open(input_json, "r") as f:
    records = json.load(f)

print("Total images to download:", len(records))
print("Starting download...\n")

downloaded = 0
skipped = 0
failed = []

for i, item in enumerate(records, start=1):
    relative_path = item["image"]

    local_path = os.path.join(
        DRIVE_ROOT,
        relative_path
    )

    # Skip if already downloaded
    if os.path.exists(local_path) and os.path.getsize(local_path) > 0:
        skipped += 1
        print(f"[{i}/500] Already exists: {relative_path}")
        continue

    os.makedirs(os.path.dirname(local_path), exist_ok=True)

    s3_path = f"{S3_ROOT}/{relative_path}"

    result = subprocess.run(
        [
            "aws",
            "s3",
            "cp",
            "--no-sign-request",
            s3_path,
            local_path
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True
    )

    if result.returncode == 0 and os.path.exists(local_path):
        downloaded += 1
        print(f"[{i}/500] Downloaded: {relative_path}")
    else:
        failed.append(relative_path)
        print(f"[{i}/500] FAILED: {relative_path}")

print("\n================================")
print("DOWNLOAD COMPLETE")
print("================================")
print("Downloaded:", downloaded)
print("Already existed:", skipped)
print("Failed:", len(failed))

if failed:
    print("\nFailed files:")
    for path in failed:
        print(path)
else:
    print("\n🎉 All 500 FMoW images are available.")

Total images to download: 500
Starting download...

[1/500] Downloaded: train/airport/airport_78/airport_78_1_rgb.jpg
[2/500] Downloaded: train/airport/airport_144/airport_144_7_rgb.jpg
[3/500] Downloaded: train/airport/airport_11/airport_11_0_rgb.jpg
[4/500] Downloaded: train/airport/airport_230/airport_230_2_rgb.jpg
[5/500] Downloaded: train/airport/airport_211/airport_211_3_rgb.jpg
[6/500] Downloaded: train/airport/airport_2/airport_2_0_rgb.jpg
[7/500] Downloaded: train/airport/airport_156/airport_156_1_rgb.jpg
[8/500] Downloaded: train/airport/airport_141/airport_141_2_rgb.jpg
[9/500] Downloaded: train/airport/airport_91/airport_91_6_rgb.jpg
[10/500] Downloaded: train/airport/airport_45/airport_45_0_rgb.jpg
[11/500] Downloaded: train/airport/airport_135/airport_135_4_rgb.jpg
[12/500] Downloaded: train/airport/airport_59/airport_59_6_rgb.jpg
[13/500] Downloaded: train/airport/airport_332/airport_332_0_rgb.jpg
[14/500] Downloaded: train/airport/airport_115/airport_115_4_rgb.jpg
[15/500] Downloaded: train/airport/airport_115/airport_115_0_rgb.jpg
[16/500] Downloaded: train/airport/airport_14/airport_14_3_rgb.jpg
[17/500] Downloaded: train/airport/airport_199/airport_199_0_rgb.jpg
[18/500] Downloaded: train/airport/airport_201/airport_201_2_rgb.jpg
[19/500] Downloaded: train/airport/airport_40/airport_40_9_rgb.jpg
[20/500] Downloaded: train/airport/airport_63/airport_63_2_rgb.jpg
[21/500] Downloaded: train/airport/airport_111/airport_111_2_rgb.jpg
[22/500] Downloaded: train/airport/airport_48/airport_48_1_rgb.jpg
[23/500] Downloaded: train/airport/airport_187/airport_187_4_rgb.jpg
[24/500] Downloaded: train/airport/airport_82/airport_82_0_rgb.jpg
[25/500] Downloaded: train/airport/airport_33/airport_33_0_rgb.jpg
[26/500] Downloaded: train/airport/airport_199/airport_199_4_rgb.jpg
[27/500] Downloaded: train/airport/airport_358/airport_358_0_rgb.jpg
[28/500] Downloaded: train/airport/airport_59/airport_59_2_rgb.jpg
[29/500] Downloaded: train/airport/airport_233/airport_233_0_rgb.jpg
[30/500] Downloaded: train/airport/airport_100/airport_100_0_rgb.jpg
[31/500] Downloaded: train/airport/airport_163/airport_163_3_rgb.jpg
[32/500] Downloaded: train/airport/airport_98/airport_98_4_rgb.jpg
[33/500] Downloaded: train/airport/airport_332/airport_332_1_rgb.jpg
[34/500] Downloaded: train/airport/airport_27/airport_27_2_rgb.jpg
[35/500] Downloaded: train/airport/airport_161/airport_161_3_rgb.jpg
[36/500] Downloaded: train/airport/airport_197/airport_197_1_rgb.jpg
[37/500] Downloaded: train/airport/airport_268/airport_268_2_rgb.jpg
[38/500] Downloaded: train/airport/airport_14/airport_14_1_rgb.jpg
[39/500] Downloaded: train/airport/airport_296/airport_296_0_rgb.jpg
[40/500] Downloaded: train/airport/airport_140/airport_140_0_rgb.jpg
[41/500] Downloaded: train/airport/airport_277/airport_277_2_rgb.jpg
[42/500] Downloaded: train/airport/airport_270/airport_270_0_rgb.jpg
[43/500] Downloaded: train/airport/airport_64/airport_64_3_rgb.jpg
[44/500] Downloaded: train/airport/airport_226/airport_226_6_rgb.jpg
[45/500] Downloaded: train/airport/airport_118/airport_118_5_rgb.jpg
[46/500] Downloaded: train/airport/airport_367/airport_367_1_rgb.jpg
[47/500] Downloaded: train/airport/airport_436/airport_436_0_rgb.jpg
[48/500] Downloaded: train/airport/airport_150/airport_150_3_rgb.jpg
[49/500] Downloaded: train/airport/airport_294/airport_294_2_rgb.jpg
[50/500] Downloaded: train/airport/airport_132/airport_132_0_rgb.jpg
[51/500] Downloaded: train/airport/airport_46/airport_46_0_rgb.jpg
[52/500] Downloaded: train/airport/airport_24/airport_24_0_rgb.jpg
[53/500] Downloaded: train/airport/airport_72/airport_72_2_rgb.jpg
[54/500] Downloaded: train/airport/airport_69/airport_69_4_rgb.jpg
[55/500] Downloaded: train/airport/airport_280/airport_280_0_rgb.jpg
[56/500] Downloaded: train/airport/airport_54/airport_54_5_rgb.jpg
[57/500] Downloaded: train/airport/airport_182/airport_182_1_rgb.jpg
[58/500] Downloaded: train/airport/airport_127/airport_127_2_rgb.jpg
[59/500] Downloaded: train/airport/airport_119/airport_119_0_rgb.jpg
[60/500] Downloaded: train/airport/airport_86/airport_86_3_rgb.jpg
[61/500] Downloaded: train/airport/airport_20/airport_20_2_rgb.jpg
[62/500] Downloaded: train/airport/airport_237/airport_237_7_rgb.jpg
[63/500] Downloaded: train/airport/airport_133/airport_133_1_rgb.jpg
[64/500] Downloaded: train/airport/airport_140/airport_140_9_rgb.jpg
[65/500] Downloaded: train/airport/airport_361/airport_361_0_rgb.jpg
[66/500] Downloaded: train/airport/airport_77/airport_77_2_rgb.jpg
[67/500] Downloaded: train/airport/airport_284/airport_284_5_rgb.jpg
[68/500] Downloaded: train/airport/airport_165/airport_165_0_rgb.jpg
[69/500] Downloaded: train/airport/airport_289/airport_289_0_rgb.jpg
[70/500] Downloaded: train/airport/airport_275/airport_275_1_rgb.jpg
[71/500] Downloaded: train/airport/airport_193/airport_193_0_rgb.jpg
[72/500] Downloaded: train/airport/airport_9/airport_9_4_rgb.jpg
[73/500] Downloaded: train/airport/airport_227/airport_227_1_rgb.jpg
[74/500] Downloaded: train/airport/airport_93/airport_93_2_rgb.jpg
[75/500] Downloaded: train/airport/airport_81/airport_81_0_rgb.jpg
[76/500] Downloaded: train/airport/airport_128/airport_128_1_rgb.jpg
[77/500] Downloaded: train/airport/airport_66/airport_66_0_rgb.jpg
[78/500] Downloaded: train/airport/airport_77/airport_77_1_rgb.jpg
[79/500] Downloaded: train/airport/airport_17/airport_17_2_rgb.jpg
[80/500] Downloaded: train/airport/airport_431/airport_431_1_rgb.jpg
[81/500] Downloaded: train/airport/airport_166/airport_166_0_rgb.jpg
[82/500] Downloaded: train/airport/airport_37/airport_37_1_rgb.jpg
[83/500] Downloaded: train/airport/airport_295/airport_295_4_rgb.jpg
[84/500] Downloaded: train/airport/airport_228/airport_228_6_rgb.jpg
[85/500] Downloaded: train/airport/airport_79/airport_79_1_rgb.jpg
[86/500] Downloaded: train/airport/airport_95/airport_95_6_rgb.jpg
[87/500] Downloaded: train/airport/airport_47/airport_47_2_rgb.jpg
[88/500] Downloaded: train/airport/airport_199/airport_199_2_rgb.jpg
[89/500] Downloaded: train/airport/airport_93/airport_93_5_rgb.jpg
[90/500] Downloaded: train/airport/airport_26/airport_26_1_rgb.jpg
[91/500] Downloaded: train/airport/airport_122/airport_122_0_rgb.jpg
[92/500] Downloaded: train/airport/airport_20/airport_20_5_rgb.jpg
[93/500] Downloaded: train/airport/airport_251/airport_251_2_rgb.jpg
[94/500] Downloaded: train/airport/airport_31/airport_31_3_rgb.jpg
[95/500] Downloaded: train/airport/airport_228/airport_228_1_rgb.jpg
[96/500] Downloaded: train/airport/airport_126/airport_126_4_rgb.jpg
[97/500] Downloaded: train/airport/airport_195/airport_195_1_rgb.jpg
[98/500] Downloaded: train/airport/airport_50/airport_50_0_rgb.jpg
[99/500] Downloaded: train/airport/airport_250/airport_250_3_rgb.jpg
[100/500] Downloaded: train/airport/airport_195/airport_195_4_rgb.jpg
[101/500] Downloaded: train/crop_field/crop_field_6516/crop_field_6516_1_rgb.jpg
[102/500] Downloaded: train/crop_field/crop_field_1706/crop_field_1706_1_rgb.jpg
[103/500] Downloaded: train/crop_field/crop_field_1157/crop_field_1157_3_rgb.jpg
[104/500] Downloaded: train/crop_field/crop_field_893/crop_field_893_3_rgb.jpg
[105/500] Downloaded: train/crop_field/crop_field_2880/crop_field_2880_5_rgb.jpg
[106/500] Downloaded: train/crop_field/crop_field_2643/crop_field_2643_0_rgb.jpg
[107/500] Downloaded: train/crop_field/crop_field_2480/crop_field_2480_1_rgb.jpg
[108/500] Downloaded: train/crop_field/crop_field_1896/crop_field_1896_0_rgb.jpg
[109/500] Downloaded: train/crop_field/crop_field_866/crop_field_866_0_rgb.jpg
[110/500] Downloaded: train/crop_field/crop_field_1653/crop_field_1653_0_rgb.jpg
[111/500] Downloaded: train/crop_field/crop_field_6864/crop_field_6864_0_rgb.jpg
[112/500] Downloaded: train/crop_field/crop_field_887/crop_field_887_1_rgb.jpg
[113/500] Downloaded: train/crop_field/crop_field_5338/crop_field_5338_0_rgb.jpg
[114/500] Downloaded: train/crop_field/crop_field_1551/crop_field_1551_2_rgb.jpg
[115/500] Downloaded: train/crop_field/crop_field_6012/crop_field_6012_0_rgb.jpg
[116/500] Downloaded: train/crop_field/crop_field_4062/crop_field_4062_4_rgb.jpg
[117/500] Downloaded: train/crop_field/crop_field_1199/crop_field_1199_1_rgb.jpg
[118/500] Downloaded: train/crop_field/crop_field_1189/crop_field_1189_5_rgb.jpg
[119/500] Downloaded: train/crop_field/crop_field_1593/crop_field_1593_4_rgb.jpg
[120/500] Downloaded: train/crop_field/crop_field_2444/crop_field_2444_3_rgb.jpg
[121/500] Downloaded: train/crop_field/crop_field_2553/crop_field_2553_4_rgb.jpg
[122/500] Downloaded: train/crop_field/crop_field_4883/crop_field_4883_7_rgb.jpg
[123/500] Downloaded: train/crop_field/crop_field_6224/crop_field_6224_0_rgb.jpg
[124/500] Downloaded: train/crop_field/crop_field_1168/crop_field_1168_4_rgb.jpg
[125/500] Downloaded: train/crop_field/crop_field_5548/crop_field_5548_1_rgb.jpg
[126/500] Downloaded: train/crop_field/crop_field_2300/crop_field_2300_0_rgb.jpg
[127/500] Downloaded: train/crop_field/crop_field_7443/crop_field_7443_0_rgb.jpg
[128/500] Downloaded: train/crop_field/crop_field_6599/crop_field_6599_1_rgb.jpg
[129/500] Downloaded: train/crop_field/crop_field_7182/crop_field_7182_0_rgb.jpg
[130/500] Downloaded: train/crop_field/crop_field_5333/crop_field_5333_2_rgb.jpg
[131/500] Downloaded: train/crop_field/crop_field_4043/crop_field_4043_3_rgb.jpg
[132/500] Downloaded: train/crop_field/crop_field_246/crop_field_246_4_rgb.jpg
[133/500] Downloaded: train/crop_field/crop_field_4317/crop_field_4317_1_rgb.jpg
[134/500] Downloaded: train/crop_field/crop_field_5991/crop_field_5991_0_rgb.jpg
[135/500] Downloaded: train/crop_field/crop_field_2897/crop_field_2897_3_rgb.jpg
[136/500] Downloaded: train/crop_field/crop_field_1039/crop_field_1039_6_rgb.jpg
[137/500] Downloaded: train/crop_field/crop_field_2032/crop_field_2032_3_rgb.jpg
[138/500] Downloaded: train/crop_field/crop_field_7135/crop_field_7135_0_rgb.jpg
[139/500] Downloaded: train/crop_field/crop_field_407/crop_field_407_4_rgb.jpg
[140/500] Downloaded: train/crop_field/crop_field_3393/crop_field_3393_6_rgb.jpg
[141/500] Downloaded: train/crop_field/crop_field_2895/crop_field_2895_3_rgb.jpg
[142/500] Downloaded: train/crop_field/crop_field_2003/crop_field_2003_0_rgb.jpg
[143/500] Downloaded: train/crop_field/crop_field_2413/crop_field_2413_0_rgb.jpg
[144/500] Downloaded: train/crop_field/crop_field_336/crop_field_336_1_rgb.jpg
[145/500] Downloaded: train/crop_field/crop_field_1651/crop_field_1651_3_rgb.jpg
[146/500] Downloaded: train/crop_field/crop_field_1589/crop_field_1589_7_rgb.jpg
[147/500] Downloaded: train/crop_field/crop_field_371/crop_field_371_3_rgb.jpg
[148/500] Downloaded: train/crop_field/crop_field_1614/crop_field_1614_1_rgb.jpg
[149/500] Downloaded: train/crop_field/crop_field_3542/crop_field_3542_2_rgb.jpg
[150/500] Downloaded: train/crop_field/crop_field_3419/crop_field_3419_3_rgb.jpg
[151/500] Downloaded: train/crop_field/crop_field_6260/crop_field_6260_0_rgb.jpg
[152/500] Downloaded: train/crop_field/crop_field_2795/crop_field_2795_0_rgb.jpg
[153/500] Downloaded: train/crop_field/crop_field_1267/crop_field_1267_5_rgb.jpg
[154/500] Downloaded: train/crop_field/crop_field_824/crop_field_824_4_rgb.jpg
[155/500] Downloaded: train/crop_field/crop_field_4419/crop_field_4419_0_rgb.jpg
[156/500] Downloaded: train/crop_field/crop_field_524/crop_field_524_0_rgb.jpg
[157/500] Downloaded: train/crop_field/crop_field_1797/crop_field_1797_3_rgb.jpg
[158/500] Downloaded: train/crop_field/crop_field_3698/crop_field_3698_5_rgb.jpg
[159/500] Downloaded: train/crop_field/crop_field_1497/crop_field_1497_2_rgb.jpg
[160/500] Downloaded: train/crop_field/crop_field_5418/crop_field_5418_3_rgb.jpg
[161/500] Downloaded: train/crop_field/crop_field_3024/crop_field_3024_2_rgb.jpg
[162/500] Downloaded: train/crop_field/crop_field_6427/crop_field_6427_2_rgb.jpg
[163/500] Downloaded: train/crop_field/crop_field_636/crop_field_636_4_rgb.jpg
[164/500] Downloaded: train/crop_field/crop_field_3564/crop_field_3564_1_rgb.jpg
[165/500] Downloaded: train/crop_field/crop_field_5794/crop_field_5794_0_rgb.jpg
[166/500] Downloaded: train/crop_field/crop_field_2252/crop_field_2252_5_rgb.jpg
[167/500] Downloaded: train/crop_field/crop_field_7236/crop_field_7236_0_rgb.jpg
[168/500] Downloaded: train/crop_field/crop_field_1433/crop_field_1433_2_rgb.jpg
[169/500] Downloaded: train/crop_field/crop_field_1282/crop_field_1282_9_rgb.jpg
[170/500] Downloaded: train/crop_field/crop_field_6699/crop_field_6699_1_rgb.jpg
[171/500] Downloaded: train/crop_field/crop_field_2518/crop_field_2518_0_rgb.jpg
[172/500] Downloaded: train/crop_field/crop_field_2997/crop_field_2997_1_rgb.jpg
[173/500] Downloaded: train/crop_field/crop_field_1501/crop_field_1501_1_rgb.jpg
[174/500] Downloaded: train/crop_field/crop_field_2554/crop_field_2554_1_rgb.jpg
[175/500] Downloaded: train/crop_field/crop_field_1641/crop_field_1641_1_rgb.jpg
[176/500] Downloaded: train/crop_field/crop_field_371/crop_field_371_9_rgb.jpg
[177/500] Downloaded: train/crop_field/crop_field_2896/crop_field_2896_1_rgb.jpg
[178/500] Downloaded: train/crop_field/crop_field_4362/crop_field_4362_0_rgb.jpg
[179/500] Downloaded: train/crop_field/crop_field_6487/crop_field_6487_10_rgb.jpg
[180/500] Downloaded: train/crop_field/crop_field_3591/crop_field_3591_0_rgb.jpg
[181/500] Downloaded: train/crop_field/crop_field_2055/crop_field_2055_1_rgb.jpg
[182/500] Downloaded: train/crop_field/crop_field_3631/crop_field_3631_0_rgb.jpg
[183/500] Downloaded: train/crop_field/crop_field_3516/crop_field_3516_1_rgb.jpg
[184/500] Downloaded: train/crop_field/crop_field_2373/crop_field_2373_1_rgb.jpg
[185/500] Downloaded: train/crop_field/crop_field_6799/crop_field_6799_2_rgb.jpg
[186/500] Downloaded: train/crop_field/crop_field_2816/crop_field_2816_0_rgb.jpg
[187/500] Downloaded: train/crop_field/crop_field_719/crop_field_719_2_rgb.jpg
[188/500] Downloaded: train/crop_field/crop_field_6935/crop_field_6935_0_rgb.jpg
[189/500] Downloaded: train/crop_field/crop_field_6582/crop_field_6582_0_rgb.jpg
[190/500] Downloaded: train/crop_field/crop_field_1445/crop_field_1445_1_rgb.jpg
[191/500] Downloaded: train/crop_field/crop_field_63/crop_field_63_0_rgb.jpg
[192/500] Downloaded: train/crop_field/crop_field_648/crop_field_648_0_rgb.jpg
[193/500] Downloaded: train/crop_field/crop_field_2114/crop_field_2114_0_rgb.jpg
[194/500] Downloaded: train/crop_field/crop_field_5209/crop_field_5209_3_rgb.jpg
[195/500] Downloaded: train/crop_field/crop_field_820/crop_field_820_2_rgb.jpg
[196/500] Downloaded: train/crop_field/crop_field_2641/crop_field_2641_1_rgb.jpg
[197/500] Downloaded: train/crop_field/crop_field_206/crop_field_206_6_rgb.jpg
[198/500] Downloaded: train/crop_field/crop_field_4446/crop_field_4446_0_rgb.jpg
[199/500] Downloaded: train/crop_field/crop_field_3706/crop_field_3706_0_rgb.jpg
[200/500] Downloaded: train/crop_field/crop_field_2835/crop_field_2835_5_rgb.jpg
[201/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_572/factory_or_powerplant_572_2_rgb.jpg
[202/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_177/factory_or_powerplant_177_3_rgb.jpg
[203/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_113/factory_or_powerplant_113_5_rgb.jpg
[204/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_670/factory_or_powerplant_670_0_rgb.jpg
[205/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_286/factory_or_powerplant_286_3_rgb.jpg
[206/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_264/factory_or_powerplant_264_4_rgb.jpg
[207/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_25/factory_or_powerplant_25_1_rgb.jpg
[208/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_193/factory_or_powerplant_193_7_rgb.jpg
[209/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_663/factory_or_powerplant_663_0_rgb.jpg
[210/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_17/factory_or_powerplant_17_5_rgb.jpg
[211/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_605/factory_or_powerplant_605_0_rgb.jpg
[212/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_67/factory_or_powerplant_67_1_rgb.jpg
[213/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_98/factory_or_powerplant_98_1_rgb.jpg
[214/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_491/factory_or_powerplant_491_2_rgb.jpg
[215/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_16/factory_or_powerplant_16_4_rgb.jpg
[216/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_528/factory_or_powerplant_528_3_rgb.jpg
[217/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_395/factory_or_powerplant_395_1_rgb.jpg
[218/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_119/factory_or_powerplant_119_1_rgb.jpg
[219/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_116/factory_or_powerplant_116_0_rgb.jpg
[220/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_163/factory_or_powerplant_163_8_rgb.jpg
[221/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_246/factory_or_powerplant_246_8_rgb.jpg
[222/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_255/factory_or_powerplant_255_0_rgb.jpg
[223/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_460/factory_or_powerplant_460_6_rgb.jpg
[224/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_537/factory_or_powerplant_537_3_rgb.jpg
[225/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_114/factory_or_powerplant_114_2_rgb.jpg
[226/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_503/factory_or_powerplant_503_9_rgb.jpg
[227/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_232/factory_or_powerplant_232_4_rgb.jpg
[228/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_639/factory_or_powerplant_639_6_rgb.jpg
[229/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_581/factory_or_powerplant_581_2_rgb.jpg
[230/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_626/factory_or_powerplant_626_1_rgb.jpg
[231/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_491/factory_or_powerplant_491_1_rgb.jpg
[232/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_394/factory_or_powerplant_394_1_rgb.jpg
[233/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_247/factory_or_powerplant_247_5_rgb.jpg
[234/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_414/factory_or_powerplant_414_1_rgb.jpg
[235/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_527/factory_or_powerplant_527_7_rgb.jpg
[236/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_288/factory_or_powerplant_288_1_rgb.jpg
[237/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_74/factory_or_powerplant_74_1_rgb.jpg
[238/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_86/factory_or_powerplant_86_0_rgb.jpg
[239/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_102/factory_or_powerplant_102_7_rgb.jpg
[240/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_688/factory_or_powerplant_688_0_rgb.jpg
[241/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_735/factory_or_powerplant_735_3_rgb.jpg
[242/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_206/factory_or_powerplant_206_3_rgb.jpg
[243/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_622/factory_or_powerplant_622_6_rgb.jpg
[244/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_396/factory_or_powerplant_396_2_rgb.jpg
[245/500] Downloaded: train/factory_or_powerplant/factory_or_powerplant_338/factory_or_powerplant_338_2_rgb.jpg

In [28]:
import os
import json

DRIVE_ROOT = "/content/drive/MyDrive/SatQuery_AI/FMoW_2015"

input_json = os.path.join(
    DRIVE_ROOT,
    "fmow_2015_final_500_training.json"
)

with open(input_json, "r") as f:
    records = json.load(f)

missing = []

for item in records:
    image_path = os.path.join(
        DRIVE_ROOT,
        item["image"]
    )

    if not os.path.isfile(image_path):
        missing.append(item["image"])

print("Total records:", len(records))
print("Images found:", len(records) - len(missing))
print("Images missing:", len(missing))

if missing:
    print("\n❌ Missing images:")
    for path in missing:
        print(path)
else:
    print("\n🎉 ALL 500 IMAGE PATHS VERIFIED SUCCESSFULLY.")

Total records: 500
Images found: 500
Images missing: 0

🎉 ALL 500 IMAGE PATHS VERIFIED SUCCESSFULLY.

In [29]:
import json
import os
from PIL import Image

DRIVE_ROOT = "/content/drive/MyDrive/SatQuery_AI/FMoW_2015"

vqa_json = os.path.join(
    DRIVE_ROOT,
    "fmow_2015_vqa_500_training.json"
)

with open(vqa_json, "r") as f:
    vqa_records = json.load(f)

print("Total VQA records:", len(vqa_records))

# Check that the first image exists
first_image = vqa_records[0]["image"]

print("First image:")
print(first_image)

print("Image exists:", os.path.exists(first_image))

img = Image.open(first_image).convert("RGB")
print("Image size:", img.size)

print("Question:", vqa_records[0]["question"])
print("Answer:", vqa_records[0]["answer"])

Total VQA records: 500
First image:
/content/drive/MyDrive/SatQuery_AI/FMoW_2015/train/airport/airport_78/airport_78_1_rgb.jpg
Image exists: True
Image size: (9636, 5655)
Question: What type of location is shown in this satellite image?
Answer: airport

In [30]:
# Qwen2-VL training collator
# Safely resizes very large FMoW images before loading them into memory.

import torch
from PIL import Image

# Allow PIL to open the very large FMoW images.
Image.MAX_IMAGE_PIXELS = None


class Qwen2VLCollator:
    def __init__(self, processor):
        self.processor = processor

    def __call__(self, batch):
        item = batch[0]   # batch size = 1

        image = Image.open(item["image"]).convert("RGB")

        # Resize extremely large images before Qwen2-VL processing.
        max_side = 2048

        if max(image.size) > max_side:
            scale = max_side / max(image.size)

            new_size = (
                int(image.width * scale),
                int(image.height * scale)
            )

            image = image.resize(new_size)

        question = item["question"]
        answer = item["answer"]

        messages = [
            {
                "role": "user",
                "content": [
                    {"type": "image"},
                    {"type": "text", "text": question}
                ]
            },
            {
                "role": "assistant",
                "content": [
                    {"type": "text", "text": answer}
                ]
            }
        ]

        prompt_messages = [
            {
                "role": "user",
                "content": [
                    {"type": "image"},
                    {"type": "text", "text": question}
                ]
            }
        ]

        full_text = self.processor.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=False
        )

        prompt_text = self.processor.apply_chat_template(
            prompt_messages,
            tokenize=False,
            add_generation_prompt=True
        )

        inputs = self.processor(
            text=[full_text],
            images=[image],
            padding=True,
            return_tensors="pt"
        )

        prompt_inputs = self.processor(
            text=[prompt_text],
            images=[image],
            padding=True,
            return_tensors="pt"
        )

        prompt_length = prompt_inputs["input_ids"].shape[1]

        labels = inputs["input_ids"].clone()

        # Calculate loss only on the assistant answer.
        labels[:, :prompt_length] = -100

        if "attention_mask" in inputs:
            labels[inputs["attention_mask"] == 0] = -100

        inputs["labels"] = labels

        return inputs


collator = Qwen2VLCollator(processor)

print("✅ Updated Qwen2-VL collator created.")
print("✅ Large FMoW images will be safely resized before processing.")

✅ Updated Qwen2-VL collator created.
✅ Large FMoW images will be safely resized before processing.

In [33]:
# Reduce image resolution for T4 GPU memory

processor.image_processor.min_pixels = 256 * 28 * 28
processor.image_processor.max_pixels = 512 * 28 * 28

print("Minimum pixels:", processor.image_processor.min_pixels)
print("Maximum pixels:", processor.image_processor.max_pixels)
print("✅ Qwen2-VL image resolution limited for T4.")

Minimum pixels: 200704
Maximum pixels: 401408
✅ Qwen2-VL image resolution limited for T4.

In [35]:
# Test large FMoW image after reducing Qwen2-VL image resolution

import torch

large_item = None

for item in vqa_records:
    with Image.open(item["image"]) as img:
        if img.width * img.height > 100_000_000:
            large_item = item
            break

if large_item is None:
    print("No image larger than 100 million pixels was found.")
    large_item = vqa_records[0]

print("Test image:")
print(large_item["image"])

with Image.open(large_item["image"]) as img:
    print("Original size:", img.size)
    print("Original pixels:", img.width * img.height)

test_batch = collator([large_item])

print("\nProcessed tensors:")

for key, value in test_batch.items():
    if hasattr(value, "shape"):
        print(f"{key}: {value.shape}")

print("\nInput token count:", test_batch["input_ids"].shape[1])
print("Image patch values:", test_batch["pixel_values"].shape[0])

torch.cuda.empty_cache()

test_batch = {
    key: value.to(model.device) if torch.is_tensor(value) else value
    for key, value in test_batch.items()
}

with torch.no_grad():
    outputs = model(**test_batch)

print("\n==============================")
print("LARGE IMAGE TEST")
print("==============================")
print("Loss:", outputs.loss.item())

if torch.isfinite(outputs.loss):
    print("✅ Large-image test successful.")
else:
    print("❌ Loss is not finite.")

Test image:
/content/drive/MyDrive/SatQuery_AI/FMoW_2015/train/airport/airport_144/airport_144_7_rgb.jpg
Original size: (14452, 14036)
Original pixels: 202848272

Processed tensors:
input_ids: torch.Size([1, 519])
attention_mask: torch.Size([1, 519])
mm_token_type_ids: torch.Size([1, 519])
pixel_values: torch.Size([1936, 1176])
image_grid_thw: torch.Size([1, 3])
labels: torch.Size([1, 519])

Input token count: 519
Image patch values: 1936

==============================
LARGE IMAGE TEST
==============================
Loss: 4.790796279907227
✅ Large-image test successful.

In [36]:
# Enable gradient checkpointing to reduce GPU memory usage during training

model.config.use_cache = False

model.gradient_checkpointing_enable(
    gradient_checkpointing_kwargs={"use_reentrant": False}
)

print("Gradient checkpointing enabled.")
print("Model cache disabled.")
print("✅ Model ready for training.")

Gradient checkpointing enabled.
Model cache disabled.
✅ Model ready for training.

In [38]:
# Training configuration

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="/content/satquery_rsvlm_lora",

    # Training
    per_device_train_batch_size=1,
    gradient_accumulation_steps=4,
    num_train_epochs=3,

    # Learning rate
    learning_rate=2e-4,
    lr_scheduler_type="cosine",
    warmup_steps=5,

    # Precision
    fp16=True,
    bf16=False,

    # Optimizer
    optim="paged_adamw_8bit",

    # Logging and saving
    logging_steps=5,
    save_strategy="epoch",
    save_total_limit=1,

    # Memory
    gradient_checkpointing=True,

    # Custom multimodal collator
    remove_unused_columns=False,

    # Other
    report_to="none",
    dataloader_num_workers=0
)

print("================================")
print("TRAINING CONFIGURATION")
print("================================")
print("Epochs:", training_args.num_train_epochs)
print("Batch size:", training_args.per_device_train_batch_size)
print("Gradient accumulation:", training_args.gradient_accumulation_steps)
print("Learning rate:", training_args.learning_rate)
print("Optimizer:", training_args.optim)
print("Scheduler:", training_args.lr_scheduler_type)
print("Precision: FP16")
print("✅ Training configuration ready.")

================================
TRAINING CONFIGURATION
================================
Epochs: 3
Batch size: 1
Gradient accumulation: 4
Learning rate: 0.0002
Optimizer: OptimizerNames.PAGED_ADAMW_8BIT
Scheduler: SchedulerType.COSINE
Precision: FP16
✅ Training configuration ready.

In [39]:
# Create the Trainer for the clean training run

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=vqa_records,
    data_collator=collator,
    processing_class=processor
)

print("================================")
print("TRAINER CREATED")
print("================================")
print("Training samples:", len(vqa_records))
print("Epochs:", training_args.num_train_epochs)
print(
    "Effective batch size:",
    training_args.per_device_train_batch_size *
    training_args.gradient_accumulation_steps
)
print("Total optimizer steps:", 375)
print("✅ Trainer is ready for the clean training run.")

================================
TRAINER CREATED
================================
Training samples: 500
Epochs: 3
Effective batch size: 4
Total optimizer steps: 375
✅ Trainer is ready for the clean training run.

In [ ]:
# Start the clean QLoRA fine-tuning run

print("================================")
print("STARTING SATQUERY AI TRAINING")
print("================================")
print("Training samples: 500")
print("Epochs: 3")
print("Total optimizer steps: 375")
print("Batch size: 1")
print("Gradient accumulation: 4")
print("================================")

train_result = trainer.train()

print("\n================================")
print("TRAINING COMPLETE")
print("================================")
print("Training finished successfully.")
print("Final training metrics:")
print(train_result.metrics)

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 151645, 'bos_token_id': None, 'pad_token_id': 151643}.

================================
STARTING SATQUERY AI TRAINING
================================
Training samples: 500
Epochs: 3
Total optimizer steps: 375
Batch size: 1
Gradient accumulation: 4
================================

[transformers] `use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.

In [43]:
import os
import shutil

source = "/content/satquery_rsvlm_lora/checkpoint-375"
destination = "/content/drive/MyDrive/SatQuery_AI/checkpoint-375"

# Make sure source exists
if not os.path.exists(source):
    raise FileNotFoundError(f"Checkpoint not found: {source}")

# Create destination parent folder
os.makedirs(
    "/content/drive/MyDrive/SatQuery_AI",
    exist_ok=True
)

# Remove an old copy only if it already exists
if os.path.exists(destination):
    shutil.rmtree(destination)

# Copy the complete checkpoint
shutil.copytree(source, destination)

print("✅ checkpoint-375 copied to Google Drive.")
print("\nSaved at:")
print(destination)

print("\nFiles:")
for file in os.listdir(destination):
    print(" -", file)

✅ checkpoint-375 copied to Google Drive.

Saved at:
/content/drive/MyDrive/SatQuery_AI/checkpoint-375

Files:
 - training_args.bin
 - adapter_config.json
 - processor_config.json
 - README.md
 - adapter_model.safetensors
 - optimizer.pt
 - scheduler.pt
 - trainer_state.json
 - scaler.pt
 - tokenizer_config.json
 - tokenizer.json
 - rng_state.pth
 - chat_template.jinja

## 8. Save and Export LoRA Adapter

In [44]:
# Save final LoRA adapter to Google Drive

import os
import shutil

final_adapter_dir = "/content/drive/MyDrive/SatQuery_AI/satquery_rsvlm_lora"

# Remove old adapter export if it exists
if os.path.exists(final_adapter_dir):
    shutil.rmtree(final_adapter_dir)

# Save trained LoRA adapter
model.save_pretrained(final_adapter_dir)
processor.save_pretrained(final_adapter_dir)

print("================================")
print("FINAL LORA ADAPTER SAVED")
print("================================")
print("Location:")
print(final_adapter_dir)

print("\nFiles:")

for file in os.listdir(final_adapter_dir):
    print(" -", file)

print("\n✅ LoRA adapter saved to Google Drive.")

================================
FINAL LORA ADAPTER SAVED
================================
Location:
/content/drive/MyDrive/SatQuery_AI/satquery_rsvlm_lora

Files:
 - README.md
 - adapter_model.safetensors
 - adapter_config.json
 - chat_template.jinja
 - tokenizer_config.json
 - tokenizer.json
 - processor_config.json

✅ LoRA adapter saved to Google Drive.

In [45]:
import os

adapter_dir = "/content/drive/MyDrive/SatQuery_AI/satquery_rsvlm_lora"

print("================================")
print("FINAL ADAPTER VERIFICATION")
print("================================")

required_files = [
    "adapter_model.safetensors",
    "adapter_config.json",
    "processor_config.json"
]

all_found = True

for file in required_files:
    path = os.path.join(adapter_dir, file)

    if os.path.isfile(path):
        size_mb = os.path.getsize(path) / (1024 * 1024)
        print(f"✅ {file} ({size_mb:.2f} MB)")
    else:
        print(f"❌ {file} MISSING")
        all_found = False

print("================================")

if all_found:
    print("🎉 FINAL LORA ADAPTER VERIFIED!")
else:
    print("❌ Verification failed.")

================================
FINAL ADAPTER VERIFICATION
================================
✅ adapter_model.safetensors (38.53 MB)
✅ adapter_config.json (0.00 MB)
✅ processor_config.json (0.00 MB)
================================
🎉 FINAL LORA ADAPTER VERIFIED!

In [47]:
# Correctly test-load the saved LoRA adapter
# using the underlying base model, not an already-wrapped PEFT model.

from peft import PeftModel

adapter_dir = "/content/drive/MyDrive/SatQuery_AI/satquery_rsvlm_lora"

print("================================")
print("CORRECT SAVED ADAPTER TEST")
print("================================")

# Get the original Qwen2-VL base model underneath the trained LoRA wrapper
base_model = model.get_base_model()

print("✅ Underlying base model obtained.")

# Load the saved LoRA adapter onto the base model
test_model = PeftModel.from_pretrained(
    base_model,
    adapter_dir,
    is_trainable=False
)

print("\n================================")
print("RESULT")
print("================================")
print("✅ Saved LoRA adapter loaded onto the base model successfully!")
print("Model type:", type(test_model))

================================
CORRECT SAVED ADAPTER TEST
================================
✅ Underlying base model obtained.

================================
RESULT
================================
✅ Saved LoRA adapter loaded onto the base model successfully!
Model type: <class 'peft.peft_model.PeftModelForCausalLM'>

In [49]:
# ============================================
# SATQUERY AI — 5-CLASS INFERENCE TEST
# ============================================

import torch
from PIL import Image

inference_model = test_model
inference_model.eval()

target_classes = [
    "airport",
    "crop_field",
    "factory_or_powerplant",
    "lake_or_pond",
    "port"
]

print("================================")
print("5-CLASS INFERENCE TEST")
print("================================")

results = []

for category in target_classes:

    # Find the first image belonging to this class
    test_item = next(
        item for item in vqa_records
        if item["category"] == category
    )

    image_path = test_item["image"]
    question = test_item["question"]
    expected_answer = test_item["answer"]

    print(f"\nTesting: {category}")
    print("Image:", image_path)

    # Load image
    image = Image.open(image_path).convert("RGB")

    # Create prompt
    messages = [
        {
            "role": "user",
            "content": [
                {"type": "image"},
                {"type": "text", "text": question}
            ]
        }
    ]

    prompt = processor.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    # Process image + prompt
    inputs = processor(
        text=[prompt],
        images=[image],
        padding=True,
        return_tensors="pt"
    )

    inputs = {
        key: value.to(inference_model.device)
        if torch.is_tensor(value) else value
        for key, value in inputs.items()
    }

    # Generate prediction
    with torch.no_grad():
        generated_ids = inference_model.generate(
            **inputs,
            max_new_tokens=30,
            do_sample=False
        )

    # Remove input tokens
    input_length = inputs["input_ids"].shape[1]

    generated_answer = processor.batch_decode(
        generated_ids[:, input_length:],
        skip_special_tokens=True
    )[0].strip()

    results.append({
        "class": category,
        "expected": expected_answer,
        "predicted": generated_answer
    })

    print("Expected:", expected_answer)
    print("Predicted:", generated_answer)

print("\n================================")
print("5-CLASS TEST RESULTS")
print("================================")

correct = 0

for result in results:
    is_correct = result["expected"].lower() in result["predicted"].lower()

    if is_correct:
        correct += 1

    status = "✅" if is_correct else "❌"

    print(
        f"{status} {result['class']} | "
        f"Expected: {result['expected']} | "
        f"Predicted: {result['predicted']}"
    )

print("\n================================")
print(f"RESULT: {correct}/5 correct")
print("================================")

================================
5-CLASS INFERENCE TEST
================================

Testing: airport
Image: /content/drive/MyDrive/SatQuery_AI/FMoW_2015/train/airport/airport_78/airport_78_1_rgb.jpg
Expected: airport
Predicted: airport

Testing: crop_field
Image: /content/drive/MyDrive/SatQuery_AI/FMoW_2015/train/crop_field/crop_field_6516/crop_field_6516_1_rgb.jpg
Expected: crop field
Predicted: crop field

Testing: factory_or_powerplant
Image: /content/drive/MyDrive/SatQuery_AI/FMoW_2015/train/factory_or_powerplant/factory_or_powerplant_572/factory_or_powerplant_572_2_rgb.jpg
Expected: factory or powerplant
Predicted: factory or powerplant

Testing: lake_or_pond
Image: /content/drive/MyDrive/SatQuery_AI/FMoW_2015/train/lake_or_pond/lake_or_pond_32/lake_or_pond_32_1_rgb.jpg
Expected: lake or pond
Predicted: lake or pond

Testing: port
Image: /content/drive/MyDrive/SatQuery_AI/FMoW_2015/train/port/port_370/port_370_3_rgb.jpg
Expected: port
Predicted: port

================================
5-CLASS TEST RESULTS
================================
✅ airport | Expected: airport | Predicted: airport
✅ crop_field | Expected: crop field | Predicted: crop field
✅ factory_or_powerplant | Expected: factory or powerplant | Predicted: factory or powerplant
✅ lake_or_pond | Expected: lake or pond | Predicted: lake or pond
✅ port | Expected: port | Predicted: port

================================
RESULT: 5/5 correct
================================

In [55]:
import os
import shutil

adapter_dir = "/content/drive/MyDrive/SatQuery_AI/satquery_rsvlm_lora"
zip_base = "/content/drive/MyDrive/SatQuery_AI/satquery_rsvlm_lora"
zip_path = zip_base + ".zip"

if os.path.exists(zip_path):
    print("✅ LoRA adapter ZIP already exists.")
    print("ZIP path:", zip_path)
else:
    zip_path = shutil.make_archive(
        zip_base,
        "zip",
        adapter_dir
    )
    print("✅ LoRA adapter ZIP created successfully.")
    print("ZIP path:", zip_path)

print("ZIP exists:", os.path.exists(zip_path))

✅ LoRA adapter ZIP already exists.
ZIP path: /content/drive/MyDrive/SatQuery_AI/satquery_rsvlm_lora.zip
ZIP exists: True